=== raphala/kafka-api-inference/experiments/kafka-python-inference-tei/inference-app/schemas/qdrant-sink-message.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Embedded Paper",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "collection_name": {
            "oneOf": [
                {
                    "type": "null",
                    "title": "Not included"
                },
                {
                    "type": "string"
                }
            ]
        },
        "id": {
            "oneOf": [
                {
                    "type": "null",
                    "title": "Not included"
                },
                {
                    "type": "string"
                }
            ]
        },
        "vector": {
            "oneOf": [
                {
                    "type": "null",
                    "title": "Not included"
                },
                {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                }
            ]
        },
        "payload": {
            "oneOf": [
                {
                    "type": "null",
                    "title": "Not included"
                },
                {
                    "$ref": "#/definitions/Payload"
                }
            ]
        }
    },
    "definitions": {
        "Payload": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "doi": {
                    "oneOf": [
                        {
                            "type": "null",
                            "title": "Not included"
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "title": {
                    "oneOf": [
                        {
                            "type": "null",
                            "title": "Not included"
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "abstract_chunk": {
                    "oneOf": [
                        {
                            "type": "null",
                            "title": "Not included"
                        },
                        {
                            "type": "string"
                        }
                    ]
                }
            }
        }
    }
}

=== raphala/kafka-api-inference/paper-inference-app/src/test/resources/expected/embeddedpaper_2.json
{
  "collection_name": "embeddings",
  "id": "4db1fd01-cb60-443a-9573-13612c772d13",
  "vector": [
    1.0,
    2.0,
    3.0,
    4.0
  ],
  "payload": {
    "doi": "10.1016/j.jhazmat.2024.136916",
    "title": "Transport of particulate mercury along the reservoir- downstream - estuary continuum during the water-sediment regulation scheme period of Yellow River in 2018.",
    "abstract_chunk": "he influence of WSRS, the Hg content in the sediments of the lower reaches to estuary continuum was affected by the variation of sediment particle size, which was caused by the difference of sediment sources. In addition, WSRS led to a change in the binding forms of Hg in sediments, from mostly binding with organic matter in the XLDR to being comprehensively restricted by organic matter, iron and manganese oxides and carbonate minerals. Therefore, the transport behaviors and deposition patterns of particulate Hg in the reservoir-downstream-estuarine continuum has a good response to the implementation process of WSRS."
  }
}
